title: Will Ballew # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  6+ years of Data Analyst experience working with Google Data Studio, querying Google Cloud SQL and Google Sheets databases.     
  <br><br>
  At BidClips I oversee all data pipeline and cleaning for 100 plus dashboards and our invoicing system.  
  By designing new databases, I develop new insights and KPIs around employee productivity.  
  I combine data from four data sources to accurately predict end-of-month revenue, profit, and subtler trends.  
  <br><br>
  <a href="https://www.linkedin.com/in/will-ball3w/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-HW2XR3C242 # your Google Analytics tracking ID here
